### ISSUE TITLE
public-cvs.squiz.net down

### ISSUE THREAD

**Issue by joshgillies** [neerolyte/vagrant-matrix#1]
With access to public-cvs.squiz.net no longer an option are there other public mirrors we can use instead?

**Comment by neerolyte** [comment]
Hey Josh, I don't think there's any public repo of any kind now (you'd have to try the forums for a more official word). The maintenance/hosting of vagrant-matrix went internal around the same time. I'll put a note up on the README mentioning this, but leave the code up on the off chance someone finds it useful.
